# Generated by Django 3.1.7 on 2021-03-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=50)),
                ('banner_toggle', models.BooleanField()),
                ('banner_path', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(null=True)),
                ('page_sequence', models.JSONField()),
                ('conset_toggle', models.BooleanField()),
                ('consent_text', models.TextField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField()),
                ('edit_response_toggle', models.BooleanField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.BigIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('qtype', models.CharField(choices=[('MC', 'Multiple Choice'), ('SP', 'Short Para'), ('LP', 'Long Para'), ('FU', 'File Upload')], max_length=2)),
                ('mandatory_toggle', models.BooleanField(default=False)),
                ('image_toggle_1', models.BooleanField(default=False)),
                ('image_path_1', models.CharField(max_length=500, null=True)),
                ('image_toggle_2', models.BooleanField(default=False)),
                ('image_path_2', models.CharField(max_length=500, null=True)),
                ('quiz_toggle', models.BooleanField(default=False)),
                ('correct_score', models.IntegerField(default=0, null=True)),
                ('incorrect_score', models.IntegerField(default=0, null=True)),
                ('title', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Short'), ('O', 'Other')], default='F', max_length=2)),
                ('partner_id', models.BigIntegerField()),
                ('sheroes_id', models.BigIntegerField()),
                ('user_type', models.CharField(choices=[('AD', 'Admin'), ('CR', 'Creator'), ('EU', 'End User')], default='EU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ShortPara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_length', models.BigIntegerField()),
                ('datatype', models.CharField(choices=[('TXT', 'Text'), ('INT', 'Integer'), ('FLT', 'Float')], default='TXT', max_length=3)),
                ('correct_answer', models.TextField(max_length=5000)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('question_sequence', models.JSONField()),
                ('randomize_toggle', models.BooleanField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='main.users')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forms')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField()),
                ('response', models.TextField(max_length=500)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forms')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
                ('image_toggle', models.BooleanField(default=False)),
                ('image_path', models.CharField(max_length=500, null=True)),
                ('correct_answer', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_mb', models.FloatField()),
                ('file_extenstion', models.CharField(max_length=10)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown_json', models.JSONField()),
                ('correct_answer', models.CharField(max_length=256, null=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
            ],
        ),
    ]
