# Generated by Django 3.1.7 on 2021-04-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortpara',
            name='correct_answer',
        ),
    ]
