# Generated by Django 3.1.7 on 2021-03-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_created_by', to='main.users'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_updated_by', to='main.users'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_created_by', to='main.users'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_updated_by', to='main.users'),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_created_by', to='main.users'),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_updated_by', to='main.users'),
        ),
    ]
