# Generated by Django 3.1.7 on 2021-04-18 19:39

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ourusers',
            managers=[
                ('objects', main.models.OurUserManager()),
            ],
        ),
    ]
