# Generated by Django 3.1.7 on 2021-04-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_shortpara_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortpara',
            name='correct_answer',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
