# Generated by Django 3.1.7 on 2021-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210316_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='page_sequence',
            new_name='section_sequence',
        ),
        migrations.AlterField(
            model_name='forms',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
