# Generated by Django 3.1.7 on 2021-03-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210316_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='conset_toggle',
            new_name='consent_toggle',
        ),
    ]
