# Generated by Django 3.1.7 on 2021-03-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210316_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
