# Generated by Django 3.1.7 on 2021-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210429_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='anonymous_response',
            field=models.BooleanField(default=True),
        ),
    ]
