# Generated by Django 3.1.7 on 2021-03-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210316_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Sections',
        ),
    ]
