# Generated by Django 3.1.7 on 2021-03-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210318_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
