# Generated by Django 3.1.7 on 2021-04-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_anonymoususer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnonymousUser',
            new_name='MyAnonymousUser',
        ),
        migrations.AddField(
            model_name='responses',
            name='anoymous_user_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responses',
            name='anoymous_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.myanonymoususer'),
        ),
    ]
