# Generated by Django 3.1.7 on 2021-04-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210430_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='user_responses',
            field=models.JSONField(default={}),
        ),
    ]
