# Generated by Django 3.1.7 on 2021-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210318_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='heading',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
