# Generated by Django 3.1.7 on 2021-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210319_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
