# Generated by Django 3.1.7 on 2021-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210319_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='banner_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forms',
            name='consent_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forms',
            name='edit_response_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forms',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
