# Generated by Django 3.2 on 2021-05-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_shortpara_limit_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='anonymous_response',
            field=models.BooleanField(default=True, help_text='Toggle to see if form accepts anonymous responses'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='banner_path',
            field=models.CharField(help_text='Path to the banner added by the user', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='banner_toggle',
            field=models.BooleanField(default=False, help_text='Boolean value to check if banner is present'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='consent_text',
            field=models.TextField(help_text='Customized consent text', null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='consent_toggle',
            field=models.BooleanField(default=False, help_text='Boolean value to check if consent is added'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='description',
            field=models.TextField(help_text='This is the description of the form', null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='edit_response_toggle',
            field=models.BooleanField(default=True, help_text='Boolean value to check if editing response is allowed'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='end_time',
            field=models.DateTimeField(help_text='End time for a form', null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='heading',
            field=models.TextField(help_text='This is the heading of the form', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check if a form is active or not'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Toggle to see if form is soft deleted'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='section_sequence',
            field=models.JSONField(help_text='This includes the sequence of the sections'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='start_time',
            field=models.DateTimeField(help_text='Start time for a form', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_score',
            field=models.IntegerField(default=0, help_text='Score for a question in quiz mode', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image_path_1',
            field=models.CharField(help_text='Path for image with question', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image_toggle_1',
            field=models.BooleanField(default=False, help_text='Toggle for image with question'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='incorrect_score',
            field=models.IntegerField(default=0, help_text='Negative marking for quiz mdoe', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='mandatory_toggle',
            field=models.BooleanField(default=False, help_text='If question is mandatory'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='other_ques_params',
            field=models.JSONField(default=dict, help_text='Other parameters for questions like short answer,integer type,file upload'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='statement',
            field=models.TextField(help_text='Question Statement'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='description',
            field=models.TextField(help_text=' Section Description', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='heading',
            field=models.TextField(help_text='Heading of a seciton', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='question_sequence',
            field=models.JSONField(help_text=' Question sequence inside sections'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='randomize_toggle',
            field=models.BooleanField(default=False, help_text='Toggle to see if questions should be randomized while displaying to end user'),
        ),
    ]
