# Generated by Django 3.1.7 on 2021-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210319_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
