# Generated by Django 3.1.7 on 2021-03-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210319_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='description',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='heading',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='randomize_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
