# Generated by Django 3.1.7 on 2021-04-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210319_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
