export const FORM_CREATE_REQUEST = 'FORM_CREATE_REQUEST';
export const FORM_CREATE_SUCCESS = 'FORM_CREATE_SUCCESS';
export const FORM_CREATE_FAILED = 'FORM_CREATE_FAILED';

export const FORM_FETCH_REQUEST = 'FORM_FETCH_REQUEST';
export const FORM_FETCH_SUCCESS = 'FORM_FETCH_SUCCESS';
export const FORM_FETCH_FAILED = 'FORM_FETCH_FAILED';

export const SECTION_CREATE_REQUEST = 'SECTION_CREATE_REQUEST';
export const SECTION_CREATE_SUCCESS = 'SECTION_CREATE_SUCCESS';
export const SECTION_CREATE_FAILED = 'SECTION_CREATE_FAILED';

export const SECTION_FETCH_REQUEST = 'SECTION_FETCH_REQUEST';
export const SECTION_FETCH_SUCCESS = 'SECTION_FETCH_SUCCESS';
export const SECTION_FETCH_FAILED = 'SECTION_FETCH_FAILED';