export const ALL_FORM_FETCH_REQUEST = 'ALL_FORM_FETCH_REQUEST';
export const ALL_FORM_FETCH_SUCCESS = 'ALL_FORM_FETCH_SUCCESS';
export const ALL_FORM_FETCH_FAILED = 'ALL_FORM_FETCH_FAILED';

export const FORM_CREATE_REQUEST = 'FORM_CREATE_REQUEST';
export const FORM_CREATE_SUCCESS = 'FORM_CREATE_SUCCESS';
export const FORM_CREATE_FAILED = 'FORM_CREATE_FAILED';

export const FORM_UPDATE_REQUEST = 'FORM_UPDATE_REQUEST';
export const FORM_UPDATE_SUCCESS = 'FORM_UPDATE_SUCCESS';
export const FORM_UPDATE_FAILED = 'FORM_UPDATE_FAILED';

export const FORM_FETCH_REQUEST = 'FORM_FETCH_REQUEST';
export const FORM_FETCH_SUCCESS = 'FORM_FETCH_SUCCESS';
export const FORM_FETCH_FAILED = 'FORM_FETCH_FAILED';

export const SECTION_CREATE_REQUEST = 'SECTION_CREATE_REQUEST';
export const SECTION_CREATE_SUCCESS = 'SECTION_CREATE_SUCCESS';
export const SECTION_CREATE_FAILED = 'SECTION_CREATE_FAILED';

export const SECTION_FETCH_REQUEST = 'SECTION_FETCH_REQUEST';
export const SECTION_FETCH_SUCCESS = 'SECTION_FETCH_SUCCESS';
export const SECTION_FETCH_FAILED = 'SECTION_FETCH_FAILED';

export const SECTION_UPDATE_REQUEST = 'SECTION_UPDATE_REQUEST';
export const SECTION_UPDATE_SUCCESS = 'SECTION_UPDATE_SUCCESS';
export const SECTION_UPDATE_FAILED = 'SECTION_UPDATE_FAILED';

export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST';
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS';
export const QUESTION_CREATE_FAILED = 'QUESTION_CREATE_FAILED';

export const QUESTION_FETCH_REQUEST = 'QUESTION_FETCH_REQUEST';
export const QUESTION_FETCH_SUCCESS = 'QUESTION_FETCH_SUCCESS';
export const QUESTION_FETCH_FAILED = 'QUESTION_FETCH_FAILED';

export const QUESTION_UPDATE_REQUEST = 'QUESTION_UPDATE_REQUEST';
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS';
export const QUESTION_UPDATE_FAILED = 'QUESTION_UPDATE_FAILED';

export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILED = 'UPLOAD_FAILED';